### ISSUE TITLE
PR2 Calibration not working on Hydro, create pr2_urdfdom solution package

### ISSUE THREAD

**Issue by UltronDestroyer** [PR2/pr2_calibration#5]
This package is to modify the urdf created by urdfdom to include the proper transmissions/tags for use by the pr2's system.

**Comment by garaemon** [comment]
The problem of current calibration process is missing several tags when reproducing urdf.
It's because of urdfdom.
we need hacked version of urdfdom like `pr2_urdfdom` and overwrite urdfdom from `pr2_calibration_launch` package.

**Comment by garaemon** [comment]
see https://github.com/PR2/pr2_calibration/pull/6

**Comment by UltronDestroyer** [comment]
This is fixed?

**Comment by garaemon** [comment]
via https://github.com/PR2/pr2_calibration/pull/6, fixed

**Comment by UltronDestroyer** [comment]
Thanks @garaemon, I'll close this issue as it is now resolved.
